# Generated by Django 3.2.7 on 2021-09-02 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='nombre')),
                ('service_amount', models.IntegerField(verbose_name='costo del servicio')),
                ('employee_amount', models.IntegerField(verbose_name='comisión del gestor')),
                ('aedo_amount', models.IntegerField(verbose_name='comisión AEDO')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='nombre')),
                ('document', models.CharField(max_length=20, verbose_name='RUC/CI')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='telefono')),
                ('cellphone', models.CharField(blank=True, max_length=20, null=True, verbose_name='celular')),
                ('address', models.TextField(blank=True, null=True, verbose_name='direccion')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='aedo.company', verbose_name='empresa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Usuario-Empresa',
                'verbose_name_plural': 'Usuario-Empresa',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_address', models.TextField(blank=True, null=True, verbose_name='dirección de origen')),
                ('destination_address', models.TextField(blank=True, null=True, verbose_name='dirección de destino')),
                ('reception_date', models.DateField(blank=True, null=True, verbose_name='fecha de retiro')),
                ('reception_time', models.TimeField(blank=True, null=True, verbose_name='hora de retiro')),
                ('deliver_date', models.DateField(blank=True, null=True, verbose_name='fecha de entrega')),
                ('deliver_time', models.TimeField(blank=True, null=True, verbose_name='hora de entrega')),
                ('service_amount', models.IntegerField(verbose_name='costo del servicio')),
                ('employee_amount', models.IntegerField(verbose_name='comisión del gestor')),
                ('aedo_amount', models.IntegerField(verbose_name='comisión AEDO')),
                ('company_amount', models.IntegerField(verbose_name='comisión de la empresa')),
                ('completed', models.BooleanField(default=False, verbose_name='rendido')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'PENDIENTE'), (1, 'RETIRADO'), (2, 'EN CAMINO'), (3, 'ENTREGADO')], default=0, verbose_name='estado')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='observaciones')),
                ('received', models.IntegerField(verbose_name='cobrado')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='aedo.city', verbose_name='ciudad')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='aedo.company', verbose_name='empresa')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='gestor')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
            },
        ),
    ]
