# Generated by Django 3.2.7 on 2021-09-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aedo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='package',
            field=models.TextField(blank=True, null=True, verbose_name='paquete'),
        ),
    ]
