# Generated by Django 3.2.7 on 2021-09-03 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aedo', '0003_alter_delivery_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Entrega', 'verbose_name_plural': 'Entregas'},
        ),
    ]
