# Generated by Django 3.2.7 on 2021-09-07 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aedo', '0004_alter_delivery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='state2',
            field=models.PositiveSmallIntegerField(choices=[(0, 'PENDIENTE DE COBRO'), (1, 'PENDIENTE DE PAGO'), (2, 'RENDIDO')], default=0, verbose_name='estado de la operación'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='gestor'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'PENDIENTE'), (1, 'RETIRADO'), (2, 'EN CAMINO'), (3, 'ENTREGADO'), [4, 'CANCELADO']], default=0, verbose_name='estado de la encomienda'),
        ),
    ]
