# Generated by Django 3.2.7 on 2021-09-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aedo', '0005_auto_20210907_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='received',
            field=models.IntegerField(default=0, verbose_name='cobrado'),
        ),
    ]
