# Generated by Django 3.2.7 on 2021-09-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aedo', '0006_alter_delivery_received'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='completed',
        ),
    ]
