# Generated by Django 3.2.7 on 2021-09-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aedo', '0009_auto_20210912_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='comment2',
            field=models.TextField(blank=True, null=True, verbose_name='comentarios del cliente'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(0, 'MALO'), (1, 'REGULAR'), (2, 'BUENO'), (3, 'MUY BUENO'), (4, 'EXCELENTE')], default=0, verbose_name='valoracion del cliente'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'PENDIENTE'), (1, 'RETIRADO'), (2, 'EN CAMINO'), (3, 'ENTREGADO'), (4, 'CANCELADO')], default=0, verbose_name='estado de la encomienda'),
        ),
    ]
